title: 三土同学
email: yao.scofiled@gmail.com
description: word changes the world

baseurl: ""
url: ""
twitter_username:
github_username:  yyyyyyyy

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
